
name: HELLO WORLD
on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build step
        run: echo "pull request done"
